### ISSUE TITLE
API _ Key  암호화 관련 

### ISSUE THREAD

**Issue by kimkyuseok** [kimkyuseok/study_git#3]
어쩌면 암호화된 키를 공유를 해야할지도 모름.  또는 특정팀 키를 새로 생성해서 관리를 하게 해야할지도. 이건 물어보자.

**Comment by kimkyuseok** [comment]
encrypted_data = b'\xc8>&;[KX\xf0\x97\x85S'
data 를 urlsafe_b64decode(encrypted_data)
urlsafe_b64decode(encrypted_data)
# Error: Incorrect padding
# # Traceback (most recent call last):
# #   File "<maya console>", line 1, in <module>
# #   File "C:\Program Files\Autodesk\Maya2023\Python\lib\base64.py", line 133, in urlsafe_b64decode
# #     return b64decode(s)
# #   File "C:\Program Files\Autodesk\Maya2023\Python\lib\base64.py", line 87, in b64decode
# #     return binascii.a2b_base64(s)
# # binascii.Error: Incorrect padding

**Comment by kimkyuseok** [comment]
``` python 

import hashlib
import pickle
from base64 import urlsafe_b64encode, urlsafe_b64decode ,b64decode
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend


key='vivestudios'
salt=b'viveStudi0sVivestudi0s'
key = hashlib.pbkdf2_hmac('sha256', key.encode(), salt, 100000)
iv = b'\x00' * 16
newCipher={}
for i in myCipher:
    data = myCipher[i]
    # 암호화
    cipher = Cipher(algorithms.AES(key), modes.CFB(iv), backend=default_backend())
    encryptor = cipher.encryptor()
    encrypted_data = encryptor.update(data.encode()) + encryptor.finalize()    
    newCipher[i] = encrypted_data


binaryString=b'\x8ad;n\x13\x17\r\xa5\xc8\xde\x07^\x8d\xcc;\xcf\xd5[\xd7VN\xe5\xa2gh'

```
